version = 1

test_patterns = [
    "ew",
    "ewgewgwe",
    "wegweg"
]

exclude_patterns = [
    "geweg",
    "ewgwgw"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_path = "github.com/mohi7solanki/dramatiq"
  dependencies_vendored = true

[[analyzers]]
name = "dockerfile"
enabled = true

  [analyzers.meta]
  dockerfile_paths = [
    "wewwqgew",
    "egw"
  ]