version = 1

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_path = "github.com/mohi7solanki/dramatiq"dependencies_vendored = "True"

[[analyzers]]
name = "dockerfile"
enabled = true

  [analyzers.meta]
  dockerfile_paths = "[&#x27;ewwlgklrg&#x27;, &#x27;rwgrlqrwglrg&#x27;]"

